### ISSUE TITLE
influx v1 auth create - ERROR

### ISSUE THREAD

**Issue by lakomika** [influxdata/influx-cli#181]
Hello
I am trying to create a configuration to connect to Kapacitor using "influx v1 auth create" but I am getting an error:
```sh

ts=2021-03-16T10:38:53.617340Z lvl=error msg="api error encountered" log_id=0SveeFdW000 error="authorization not found"
```
The script which adds a docker container (located in the docker-entrypoint-initdb.d folder) during creation:

```
influx v1 auth create \
 --username ${DOCKER_INFLUXDB_INIT_USERNAME} \
 --read-bucket ${DOCKER_INFLUXDB_INIT_BUCKET_ID} \
 --write-bucket ${DOCKER_INFLUXDB_INIT_BUCKET_ID} \
 --password ${DOCKER_INFLUXDB_INIT_PASSWORD} \
 --token ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN} \
 --org ${DOCKER_INFLUXDB_INIT_ORG} 
```

**Comment by jeffreyssmith2nd** [comment]
@Pwuts I think you're running into a slight confusion around the auth system (which is understandable, because it is not the most straightforward).

An influx user is supposed to map to a person that logs in to the UI. Users have a username and password. The `--token` flag on the `user create` command is to authorize the action, not to set a token for the user.

If you are trying to setup a Telegraf configuration, you need to use an `auth`. https://docs.influxdata.com/influxdb/v2.6/reference/cli/influx/auth/create/

There is currently no support for supplying your own token, so the best route would be to create an auth with the expected permissions, capture the resulting token, and then supply that to telegraf.

**Comment by Pwuts** [comment]
@jeffreyssmith2nd ah, THANK YOU for clearing that up, only cost me ~5 hours of trying to debug so far.. :')

Is this in the documentation somewhere?

**Comment by jeffreyssmith2nd** [comment]
I thought it was, but I've looked around and haven't found anything. I'll think about how we can improve the documentation around this a little better.
