### ISSUE TITLE
Cannot change password in Windows - confirmation skipped with error

### ISSUE THREAD

**Issue by hybuild-project** [influxdata/influx-cli#189]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Fresh installation using UI and adding ```admin|password|example|test``` as defaut user|pwd|org|bucket
2. .Enter ```\influx user password -n admin``` in PowerShell
3. Type as password ```12345678```

__Expected behavior:__
After Enter, a confirmation is asked

__Actual behavior:__
The confirmation immediately return an error
```
←[36mPlease type your new password←[0m:

←[36mPlease type your new password again←[0m:

←[31mPasswords do not match.
←[0m←[36mPlease type your new password←[0m:

```
__Environment info:__

* System info: Win10
* InfluxDB version: 2.0.6 (win binaries)

__Additional info:__

The same behaviour happens running ```influx setup``` on a fresh installation via CLI.

**Comment by danxmoran** [comment]
At least for `influx setup`, I see this is fixed in the new CLI implementation contained in this repo. It should roll out with v2.1.0 of the CLI, which we hope to release soon (this week or next). I'd expect the fix to also apply to `influx user password` but I haven't tested it myself yet.

@hybuild-project @jey07 if you're willing to test a pre-release, could you try out [this PR build](https://2437-356362815-gh.circle-artifacts.com/0/dist/influx_windows_amd64/influx.exe) (download from CircleCI's S3 bucket) and let me know if it addresses your problem?

**Comment by danxmoran** [comment]
#88 would also help work around this; if the interactive prompt is still broken for you, I'll try to get that feature bundled into the upcoming release

**Comment by danxmoran** [comment]
I believe this should be fixed as of the latest CLI release, closing
