### ISSUE TITLE
InfluxDB Cloud Map type customization not included in influx export

### ISSUE THREAD

**Issue by abalone23** [influxdata/influx-cli#209]
InfluxDB Cloud Map visualization type has an option to use S2 Cell ID or lat/lon fields, which are selectable.
<img width="414" alt="influxcloud-map-customize" src="https://user-images.githubusercontent.com/330044/127230327-dbe1e6ea-aa2d-4ed9-87a9-0091b80d4334.png">

However, this option is not included when exporting the dashboard using the latest nightly cli:
[sensor_cli_export.yml.txt](https://github.com/influxdata/influx-cli/files/6888859/sensor_cli_export.yml.txt)
```
Influx CLI nightly-2021-07-27 (git: 7efea59) build_date: 2021-07-27T05:14:43Z
influx export all --filter=resourceKind=Dashboard --filter=labelName=sensor
```

It is included when exporting the dashboard via the UI:
[sensor_export_ui.json.txt](https://github.com/influxdata/influx-cli/files/6888860/sensor_export_ui.json.txt)
```
            "useS2CellID": false,
            "s2Column": "",
            "latLonColumns": {
              "lat": {
                "key": "tag",
                "column": "lat"
              },
              "lon": {
                "key": "tag",
                "column": "lon"
              }
```

**Comment by danxmoran** [comment]
I don't believe this is a bug in the CLI, though I can see that it's a confusing difference from the UI.

The CLI's `export` command uses the `/templates/export` endpoint to download resource metadata. The code is agnostic to the fields in the `spec` of each exported resource; it parses whatever the server returns as a generic `map[string]interface{}`, then writes that as either YAML or JSON. If the server's response is "missing" fields, the CLI won't notice. This design choice was made to decouple the CLI from the specifics of the server `pkger`, so we don't have to do a CLI release every time a change is made on the server side.

The UI uses entirely different logic to export a dashboard. Instead of a single call to `/templates/export`, it uses multiple API calls to fetch all the resource metadata:
* `/dashboards/<dashboard-id>`
* `/dashboards/<dashboard-id>/cells/<cell-id>/view` (per-cell)

I'm guessing there are differences in how dashboard cells get serialized between the two sets of endpoints. Will investigate before closing.

**Comment by danxmoran** [comment]
The server-side fix has merged to InfluxDB Cloud, I now see `s2Column` and `latLonColumns` in export responses from my account. Closing this.
