### ISSUE TITLE
firstMile Onboarding - InfluxCLI - Update all OS downloads to include a URL with "latest" in the title - route to latest version

### ISSUE THREAD

**Issue by Luckette** [influxdata/influx-cli#394]
## Ask
In support of the firstMile Onboarding initiative to increase activated user accounts, we'd like InfluxCLI download links for all operating systems to include a URL with "latest" in the title that routes to the latest version of the CLI. 

## ACs
- For Mac OS, make sure that the download text for CLI has the latest version number routed to "latest" so that the text displays "latest" rather than specific version numbers. 
- For Windows OS, make sure that the download text for CLI has the latest version number routed to "latest" so that the text displays "latest" rather than specific version numbers. 
- For Linux, make sure that the download text for CLI has the latest version number routed to "latest" so that the text displays "latest" rather than specific version numbers. 
- Implement automation that automatically routes the latest version to the URLs w/ "latest" in the text

## Example
change:
https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.3.0-linux-amd64.tar.gz

to:
https://dl.influxdata.com/influxdb/releases/influxdb2-client-latest-linux-amd64.tar.gz

**Comment by Luckette** [comment]
FYI @kristinarobinson

**Comment by dgnorton** [comment]
@bnpfeife this is related to the InfluxCLI but probably doesn't involve a change to the CLI itself. Thoughts on the right way to have a "latest" link always download the latest version of the CLI? I think S3 buckets support a notion of symlinks or aliases. Could the process that pushes binaries also create "latest" aliases?

**Comment by bnpfeife** [comment]
Unfortunately, I couldn't find any information regarding S3 supporting symlinks.

We could use CloudFront and a Lambda function to rewrite the request location to point it at the correct artifact. Otherwise, there is CloudFront configuration that would allow us to setup redirections. The downside of these approaches is that they require active management. With each deployment, these would need to be rewritten with the updated artifact locations.

I think the easiest solution, would be to upload duplicate artifacts on each deployment. Since the latest artifact name is the same on each deployment, we would need to contact SRE about invalidating the CloudFront cache.

**Comment by samhld** [comment]
@tkyocum any thoughts on Brandon's comment here?

**Comment by samhld** [comment]
Closed via
