### ISSUE TITLE
influx cli: cannot create auth: Error: Id must have a length of 16 bytes.

### ISSUE THREAD

**Issue by russorat** [influxdata/influx-cli#69]
```
➜  influxdb git:(add-docker) ✗ ./bin/darwin/influx auth create --write-bucket node_metrics_v1
Error: Id must have a length of 16 bytes.
See 'influx auth create -h' for help
```

Looks like this only happens if use the wrong command line flag. the following works fine (write-bucketS):
```
./bin/darwin/influx auth create --write-buckets node_metrics_v1
```

**Comment by danxmoran** [comment]
Closing this as a "won't fix" as my impression is that we're trying to push the CLI & API towards usage of IDs over names as much as possible.

I think the fact that `--write-buckets` worked in the original report was either a bug in the CLI parser or a relic of an API that's since changed. That flag is now a no-arg boolean that toggles permissions for all buckets within a single org.

**Comment by 632691987** [comment]
I just have the same problem. 

Resolved, because you said your Organization NAME as what you input, actually, you should input the ID, not NAME, the ID is generated by the InfluxDB.
