### ISSUE TITLE
InfluxDB2 - org members list fails for more than 10 members

### ISSUE THREAD

**Issue by mproffitt** [influxdata/influx-cli#91]
We are seeing an issue with influxdb version 2 <= 2.0.6 whereby if an organisation is given more than 10 members, listing members of that organisation then hangs indefinitely.

Steps to reproduce:
- Create new organisation
- Create an arbitrary number of users > 10
- Assign 11 of those users to the new organisation
- `influxdb -t <token> org members list -n <org-name>

Operating system details (platform 1)
- Amazon EKS stack with 3 nodes (Amazon Linux 64bit)
- 8cpu per node
- 16Gb ram

Operating system (platform 2 - confirmation)
- Debian 10 64bit
- 4 core
- 32Gb ram

`influxdb version 2.0.6 (docker run influxdb2:2)`

Also confirmed on influxdb 2.0.1 running on the EKS stack described above

**Comment by danxmoran** [comment]
I see the problem: the CLI logic gets the IDs of all members in an org, then parallelizes requests to get more info for each user. It attempts to limit the number of concurrent HTTP requests using a bounded channel, but the logic is written so that if there are more users than the hard-coded limit then the whole program will block.
